name: Sync with Hugging Face Repo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-hf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3

    - name: Clone Hugging Face repo
      run: |
        git clone https://huggingface.co/datasets/SEAL-IIT-KGP/XPACT.git
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
